name: hiercadnet_lin
channels:
        - defaults
        - conda-forge
dependencies:
        - python=3.9
        - numpy
        - h5py
        - scikit-learn
        - pip
        - pip:
                - tensorflow[and-cuda]
