name: hiercadnet_lin
channels:
        - defaults
        - conda-forge
dependencies:
        - python=3.8
        - numpy
        - h5py
        - scikit-learn
        - pythonocc-core=7.5.1
        - occt=7.5.1
        - pip
        - pip:
                - tensorflow